apiVersion: apps/latest
kind: Deployment
metadata:
  name: todolist-deployment
  labels:
    app: todolist
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
      - name: todolist
        image: gcr.io/{{PROJECT_ID}}/todolist:latest
        ports:
        - containerPort: 5000
